### ISSUE TITLE
Swap the label text and visits count

### ISSUE THREAD

**Issue by dashroshan** [roshan1337d/visits-counter#1]
## What needs to be done

When a query `swap=1` is passed with the badge link, swap the label text and visits count so that the label is on the right, and the visits count is on the left. Ignore if `swap=0` or if this query parameter is absent.

## Tips

You would just need to check for the `swap` parameter [here](https://github.com/roshan1337d/visits-counter/blob/6d5096f0c487b67bddba1d92bbffb4b44b34b617/index.js#L27) and switch the label and visits values [here](https://github.com/roshan1337d/visits-counter/blob/6d5096f0c487b67bddba1d92bbffb4b44b34b617/index.js#L41)

**Comment by MiTo0o** [comment]
can I have this one

**Comment by kritiag20** [comment]
I want to work o this issue please assign it to me

**Comment by dashroshan** [comment]
@MiTo0o assigned this to you

@kritiag20 Assigning it to MiTo0o on a first come basis. In case s/he isn't able to complete this, I will assign it to you.

Happy hacktober 🚀
