### ISSUE TITLE
Document the query parameters with examples in README.md

### ISSUE THREAD

**Issue by dashroshan** [roshan1337d/visits-counter#2]
## What needs to be done

Document the available query parameters that can be passed with the badge image link. Describe their possible values, and what sort of customizations each of them does. Refer to [here](https://github.com/roshan1337d/visits-counter/blob/6d5096f0c487b67bddba1d92bbffb4b44b34b617/index.js#L28) for the parameters, and use the [site](https://visits.roshan.cyou/) to see how each of them affect the badge. Provide a few examples.

## Tips

You may create a table like the below:

| **Parameter** | **Values** | **Customization** |
| --- | --- | --- |
| shadow | 1 or 0 | Turns the text shadow for the label and visits count on and off respectively |

Markdown code for the above table:

```
| **Parameter** | **Values** | **Customization** |
| --- | --- | --- |
| shadow | 1 or 0 | Turns the text shadow for the label and visits count on and off respectively |
```

**Comment by Misterr-H** [comment]
@roshan1337d 
Hello, I would like to work upon this

**Comment by dashroshan** [comment]
@Misterr-H assigned this to you, happy hacktober 🚀

**Comment by Misterr-H** [comment]
@roshan1337d 
Thanks
I'm on it

**Comment by Misterr-H** [comment]
hello @roshan1337d 
Please review this table
<img width="457" alt="Screenshot 2022-10-02 at 4 56 57 PM" src="https://user-images.githubusercontent.com/55010619/193451597-09707da4-8a53-482f-9cb4-62393fee3b8e.png">

**Comment by dashroshan** [comment]
Looking good. Few suggestions:

- For values and customization, keep only the first characters in uppercase and make the rest lowercase.
- Remove the last 'text' in customization
- change count to visits count in customization

Also make a few examples using different number of query parameters.

**Comment by Misterr-H** [comment]
hello @roshan1337d 
here are final things
<img width="431" alt="Screenshot 2022-10-02 at 5 33 11 PM" src="https://user-images.githubusercontent.com/55010619/193452999-2cb28490-7db0-49ad-ab72-63446180d990.png">
<img width="453" alt="Screenshot 2022-10-02 at 5 33 20 PM" src="https://user-images.githubusercontent.com/55010619/193453011-05e41dd0-2217-47a9-8a57-a49ae71371d3.png">

**Comment by dashroshan** [comment]
Looks good, just change one of the examples to have text shadow off and open a PR

**Comment by Misterr-H** [comment]
@roshan1337d done
Please don't forget to label with hacktoberfest-accepted while merging
thanks
