### ISSUE TITLE
Colors not updating when using scrollbar

### ISSUE THREAD

**Issue by eventually-delete** [roshan1337d/visits-counter#5]
Hey, I observed that label background color, label text color and visits count text color do not change when first moving the scrollbar at the color picker. Once you pick a color selecting it over the color paddle the color updates even using the scrollbar. This do not happens in the visits count background color. 

I would like to try and solve this, yet I'm afraid with my current knowledge I haven't been able to, hope you can give me some tip.

![Screenshot from 2022-10-02 13-24-38](https://user-images.githubusercontent.com/92840840/193452454-6c38255c-29a3-4366-a485-770ef77957f1.png)
![Screenshot from 2022-10-02 13-24-43](https://user-images.githubusercontent.com/92840840/193452455-6610f110-b83d-4d69-9ea6-9a02cdc63b70.png)
![Screenshot from 2022-10-02 13-24-51](https://user-images.githubusercontent.com/92840840/193452456-42a1852c-2503-4332-b9ed-818221cb5421.png)
![Screenshot from 2022-10-02 13-24-58](https://user-images.githubusercontent.com/92840840/193452457-180bb067-9e71-4215-8d32-b773e48d13b3.png)

**Comment by dashroshan** [comment]
This isn't actually a bug. The default color for label background color, label and visits count text color are grey and white respectively which are zero saturation colours (the circle is on the left edge) and remains the same irrespective of any base colour you choose using the scrollbar. If you add some saturation by moving the circle away from the left most edge, the scroll bar starts affecting the colour. That is how usual color combinations work.

Thanks for your interest though, happy hacktober :)

**Comment by eventually-delete** [comment]
Oh I see, didn't know about that, my bad! Thanks for the feedback :)
