### ISSUE TITLE
Implement the swap feature for web tool

### ISSUE THREAD

**Issue by dashroshan** [roshan1337d/visits-counter#8]
### 1

Passing a query parameter `swap=1` with the image link like `https://visits.roshan.cyou/uniqueid?swap=1` swaps the position of the label and visits count. Add a toggle button like that for the text shadow in the [web tool](https://visits.roshan.cyou) for this swap feature. It should affect the live preview as well as the copy link and embed codes accordingly.

### 2

The [swapping code](https://github.com/roshan1337d/visits-counter/blob/acba68087f7e136aff35c0d4b0fd5a42500f1068/index.js#L42) is currently in the root index.js file for the backend. Move it to the [svgBadge.js](https://github.com/roshan1337d/visits-counter/blob/master/frontend/src/svgBadge.js) file so that you can just pass the swap value as a parameter to the svgBadge function for the swapping instead of repeating the logic for both frontend and backend.

**Comment by brandonmcconnell** [comment]
@roshan1337d Can I take this one? Do you have a preference on how I read the query param value(s) or do you already have a function for that?

**Comment by dashroshan** [comment]
Sure, assigned it to you 👍

The [backend](https://github.com/roshan1337d/visits-counter/blob/acba68087f7e136aff35c0d4b0fd5a42500f1068/index.js#L36) reads it like `"0"` or `"1"`. So you can either call the svgBadge function that way from the react site, or modify the svgBadge function for it to work with both `"0" or "1"` strings and `true or false` booleans similar to how I did it [here](https://github.com/roshan1337d/visits-counter/blob/acba68087f7e136aff35c0d4b0fd5a42500f1068/frontend/src/svgBadge.js#L43). That is what you were asking, right?

**Comment by brandonmcconnell** [comment]
@roshan1337d Thanks, that helps!

Do you have a preferred way of retrieving the param keys and values themselves, for example…
* [`window.location.search`](https://developer.mozilla.org/en-US/docs/Web/API/Location/search)
* vs. [`useParams`](https://reactrouter.com/en/main/hooks/use-params) for use with React Router

**Comment by dashroshan** [comment]
@brandonmcconnell a static build of the react site is used by the express server for just the root path. All parameters and queries are managed by the express server and not the react site.

**Comment by brandonmcconnell** [comment]
Ahh gotcha. I'm not too experienced with Express, so I'll go ahead and unassign myself so you can find someone more qualified for this task. Thanks, and best of luck!

**Comment by dashroshan** [comment]
@brandonmcconnell this task doesn't involve the express backend at all. The react site gets all the values from the user inputs in customizations section of the site, passes them to the svgBadge function which returns the svg code, displays the svg badge, and combines all the customizations to make the link with the query (as a string). The site is a query builder with live preview.

Let me know if that sounds doable and you want to be reassigned. Its alright otherwise.

**Comment by brandonmcconnell** [comment]
Sorry, it does sound doable. I'm just not sure exactly how to access the URL search params via Express. Is there a place on the site you're already doing this so I can see how you're doing that?

**Comment by dashroshan** [comment]
Seems like we're having difficulty communicating, so it might be better for someone else to take this up.

Anyone else interested let me know.
