### ISSUE TITLE
Customizable shadow opacity

### ISSUE THREAD

**Issue by dashroshan** [roshan1337d/visits-counter#9]
## What needs to be done

Passing a `shadowOpacity=x` query should change the text-shadow opacity of the badge. For example: `https://visits.roshan.cyou/test?shadowOpacity=50` should make the shadow with 50% opacity. If this query isn't passed, it should be 30% by default.

## Tips

- Get the query [here](https://github.com/roshan1337d/visits-counter/blob/8da5e7083bc46fe52f3c6844bf5cfb4a39add109/index.js#L36) and make the default 30 instead of 0.
- Modify the [svgBadge](https://github.com/roshan1337d/visits-counter/blob/8da5e7083bc46fe52f3c6844bf5cfb4a39add109/frontend/src/svgBadge.js#L50) function to accept one more argument for opacity.
- Then pass the opacity value [here](https://github.com/roshan1337d/visits-counter/blob/8da5e7083bc46fe52f3c6844bf5cfb4a39add109/frontend/src/svgBadge.js#L35) dividing it by 100 (30% -> 0.3) to affect the text-shadow.

**Comment by isurumaldeniya** [comment]
@roshan1337d Hi, I would like to work on this issue. Can you please assign this to me?

**Comment by isurumaldeniya** [comment]
@roshan1337d Hi I have sent a PR following your guideline. Please review it and let me know if anything needed to be changed.
